#!/bin/sh

set -e

# Compile module .py to .pyc
python -m compileall -f /usr/lib/python2.6/site-packages/pdagent/

# Compile bin .py to .pyc
python -m compileall /usr/bin/pd-*.py

# Register daemon
#update-rc.d -f pd-agent defaults


