#!/bin/sh

set -e

# Compile .py to .pyc
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules  python-pdagent.public
fi

# Install daemon init script
update-rc.d -f pd-agent defaults

