ARG UBUNTU_VERSION=16.04
FROM ubuntu:${UBUNTU_VERSION}

ARG FPM_VERSION=1.11.0
ARG PYTHON_VERSION=3
ENV PYTHON_VERSION ${PYTHON_VERSION}
ENV container docker
ENV DEBIAN_FRONTEND noninteractive
ENV DOCKER_DEV_ENV true

RUN apt-get update -y -qq
RUN apt-get install -y -q apt-utils
RUN apt-get install -y -q build-essential
RUN apt-get install -y -q ca-certificates
RUN apt-get install -y -q python-software-properties
RUN apt-get install -y -q ruby2.3
RUN apt-get install -y -q ruby2.3-dev
RUN apt-get install -y -q software-properties-common
RUN apt-get install -y -q sudo
RUN apt-get install -y -q systemd
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN update-ca-certificates

RUN gem install -q --no-ri --no-rdoc -v ${FPM_VERSION} fpm
RUN apt-get install -y -q python${PYTHON_VERSION}
RUN cd /lib/systemd/system/sysinit.target.wants/ \
    && ls | grep -v systemd-tmpfiles-setup | xargs rm -f $1

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/basic.target.wants/* \
    /lib/systemd/system/anaconda.target.wants/* \
    /lib/systemd/system/plymouth* \
    /lib/systemd/system/systemd-update-utmp*

VOLUME [ "/sys/fs/cgroup" ]

WORKDIR /pd-agent-install
COPY . /pd-agent-install
RUN  mkdir -p /pd-agent-install/build-linux/fancycat
RUN  cd /pd-agent-install/build-linux && ./make_deb.sh /pd-agent-install/build-linux/gnupg /pd-agent-install/build-linux/fancycat
RUN  echo "Installing debian package"

# Installing the debian package will also enable pdagent in systemd
RUN dpkg -i /pd-agent-install/build-linux/fancycat/deb/pdagent_1.6_all.deb

CMD ["/lib/systemd/systemd"]
