FROM rockylinux:8

ARG FPM_VERSION=1.16.0
ARG PYTHON_VERSION=3
ARG DOCKER_WORKDIR=/usr/share/pdagent
ARG SKIP_SYSTEMD=false
ENV PYTHON_VERSION ${PYTHON_VERSION}
ENV container docker
ENV DOCKER_WORKDIR ${DOCKER_WORKDIR}
ENV SKIP_SYSTEMD ${SKIP_SYSTEMD}

# Install Ruby 3 instead of system Ruby 2.x
RUN dnf install -y epel-release
RUN dnf module reset ruby
RUN dnf module enable -y ruby:3.0
RUN dnf install -y createrepo gcc gcc-c++ kernel-devel make python3-pip rpm-build rpm-sign ruby ruby-devel sudo which initscripts redhat-rpm-config

# Prevent gem from updating dotenv to a newer version as a dependency
RUN gem install -q --no-document -v 1.15.5 ffi
RUN gem install -q --no-document -v ${FPM_VERSION} fpm

RUN dnf install -y python${PYTHON_VERSION}

COPY . $DOCKER_WORKDIR
WORKDIR $DOCKER_WORKDIR

CMD ["/usr/sbin/init"]