FROM centos/systemd

ARG FPM_VERSION=1.11.0
ARG PYTHON_VERSION=3
ENV PYTHON_VERSION ${PYTHON_VERSION}

ENV container docker
ENV DOCKER_DEV_ENV true

RUN yum install -y -q centos-release-scl
RUN yum install -y -q createrepo
RUN yum install -y -q gcc
RUN yum install -y -q gcc-c++
RUN yum install -y -q kernel-devel
RUN yum install -y -q make
RUN yum install -y -q python27-python-pip
RUN yum install -y -q python3-pip
RUN yum install -y -q rpm-build
RUN yum install -y -q rpm-sign
RUN yum install -y -q rh-ruby23
RUN yum install -y -q rh-ruby23-ruby-devel
RUN yum install -y -q sudo
RUN yum install -y -q which

RUN source /opt/rh/rh-ruby23/enable && \
  /opt/rh/rh-ruby23/root/usr/bin/gem install -q --no-ri --no-rdoc -v $FPM_VERSION fpm
RUN yum install -y python${PYTHON_VERSION}

WORKDIR /pd-agent-install
COPY . /pd-agent-install
RUN  mkdir -p /pd-agent-install/build-linux/release
RUN  cd /pd-agent-install/build-linux && ./make_rpm.sh /pd-agent-install/build-linux/gnupg /pd-agent-install/build-linux/release
RUN  echo "Installing rpm package"

RUN ./scripts/build.sh centos

CMD ["/usr/sbin/init"]
