#!/bin/sh
#
# Copyright (c) 2013-2014, PagerDuty, Inc. <info@pagerduty.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#   * Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

set -e

install_init () {
    cp /var/lib/pdagent/scripts/pdagent.init /etc/init.d/pdagent
    chmod +x /etc/init.d/pdagent
    chkconfig --add pdagent
    service pdagent restart
}

install_systemd () {
    if [ -d "/lib/systemd/system" ]
    then
        cp /var/lib/pdagent/scripts/pdagent.service /lib/systemd/system
    else
        cp /var/lib/pdagent/scripts/pdagent.service /etc/systemd/system
    fi
    systemctl enable pdagent
    systemctl start pdagent
}

# Create pdagent user & group
/usr/bin/getent passwd pdagent >/dev/null || \
    /usr/sbin/adduser --system --shell /bin/false --no-create-home pdagent

# Fix ownership of data and log dirs.
# outqueue/* world permission is set to 000 so that service keys of other
# users cannot be seen, but set to -wx for enqueue-related directories
# to allow any user to write events.
chown -R pdagent:pdagent /var/lib/pdagent /var/log/pdagent
chmod 2750 /var/lib/pdagent/outqueue/err /var/lib/pdagent/outqueue/suc
chmod 2753 /var/lib/pdagent/outqueue/tmp /var/lib/pdagent/outqueue/pdq

VERSION=`python -c "import platform; print(platform.python_version())"`
if [[ $VERSION == 3* ]]; then
    INSTALL_PATH="/usr/lib/python3/site-packages/pdagent"
elif [[ $VERSION == 2.7.* ]]; then
    INSTALL_PATH="/usr/lib/python2.7/site-packages/pdagent"
else
    INSTALL_PATH="/usr/lib/python2.6/site-packages/pdagent"
fi

# ensure that our root certs are readable
chmod -R a+r $INSTALL_PATH/root_certs

# Compile module .py to .pyc
python -m compileall -q -f "$INSTALL_PATH/"

if [ <%= skip_systemd %> = false ] && which systemctl >/dev/null; then
    install_systemd
else
    install_init
fi

exit 0
