#!/bin/sh

set -e

case "$*" in
    0)  # remove-only; not upgrade.
        # Stop daemon
        service pdagentd stop

        # Unregister daemon
        chkconfig --del pdagentd

        # Clean up module .pyc
        find /usr/lib/python2.6/site-packages/pdagent/ \
            -name "*.pyc" -exec rm {} \;
        ;;
    *)
        ;;
esac

exit 0

