version: 2
jobs:
  test-py2:
    docker:
      - image: circleci/python:2.7.17
    steps:
      - checkout
      - run: make test
  test-py3:
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run: make test
  test-install-ubuntu-py3:
    steps:
      - checkout
      - run: make build-ubuntu && make install-ubuntu-test
  test-install-ubuntu-py2:
    steps:
      - checkout
      - run:
        environment:
          PYTHON_VERSION: ''
        command: make build-ubuntu && make install-ubuntu-test
workflows:
  version: 2
  test:
    jobs:
      - test-py2
      - test-py3
      - test-install-ubuntu-py3
      - test-install-ubuntu-py2
