version: 2
jobs:
  build:
    test-py2:
      docker:
        - image: circleci/python:2.7.17
      steps:
        - checkout
        - run: make test
    test-py3:
      docker:
        - image: circleci/python:3.7.6
      steps:
        - checkout
        - run: make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-py2
      - test-py3