#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    # Create pdagent user & group
    /usr/bin/getent passwd pdagent >/dev/null || \
        /usr/sbin/adduser --system --shell /bin/false --no-create-home \
            --group pdagent

    # Fix ownership of data and log dirs
    chown -R pdagent:pdagent /var/run/pdagent /var/lib/pdagent /var/log/pdagent
    chmod 777 /var/lib/pdagent/outqueue

    # Compile module .py to .pyc
    if which update-python-modules >/dev/null 2>&1; then
        update-python-modules python-pdagent.public
    fi

    # Register daemon
    update-rc.d -f pd-agent defaults

    # Restart daemon
    #FIXME: daemon is broken
    #if which invoke-rc.d >/dev/null 2>&1; then
    #    invoke-rc.d pd-agent restart
    #else
    #    /etc/init.d/pd-agent restart
    #fi
fi

exit 0
