#!/bin/sh

set -e

# Compile module .py to .pyc
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules python-pdagent.public
fi

# Compile bin .py to .pyc
python -m compileall -f /usr/bin/pd-*.py

# Register daemon
update-rc.d -f pd-agent defaults

