#!/bin/sh

set -e

if [ "$1" = "remove" ]; then  # remove-only; not upgrade.
    # Stop daemon
    service pdagentd stop

    # Unregister daemon
    update-rc.d -f pdagentd remove

    # Clean up module .pyc
    if which update-python-modules >/dev/null 2>&1; then
        update-python-modules -c python-pdagent.public
    fi
fi

exit 0
